import type { Tour, VehicleModel, VehicleType } from "./types";

// Real photos uploaded in /admin always win; otherwise use the site's original
// illustrations (generated by scripts/gen-art.ts — no third-party artwork).
const ART: Record<VehicleType, string> = { atv: "atv", utv: "atv", dirtbike: "dirtbike", scooter: "scooter" };

/** Wide image (detail pages). */
export const vehicleImage = (m: Pick<VehicleModel, "images" | "type">) => m.images[0] ?? `/images/vehicles/${ART[m.type]}.svg`;
/** Narrow image for card thumbnails — the vehicle stays fully in frame. */
export const vehicleThumb = (m: Pick<VehicleModel, "images" | "type">) => m.images[0] ?? `/images/vehicles/${ART[m.type]}-card.svg`;
export const tourImage = (t: Pick<Tour, "images" | "category">) => t.images[0] ?? `/images/tours/${t.category}.svg`;

/** Local SVG illustrations skip the image optimizer (it doesn't rasterize SVG). */
export const isIllustration = (src: string) => src.endsWith(".svg");

export const HERO_IMAGE = "/images/hero-sunset.svg";
