import type { Tour, VehicleModel, VehicleType } from "./types";

// Real photos uploaded in /admin always win; otherwise use the site's original
// illustrations (generated by scripts/gen-art.ts — no third-party artwork).
const VEHICLE_ART: Record<VehicleType, string> = {
  atv: "/images/vehicles/atv.svg",
  utv: "/images/vehicles/atv.svg",
  dirtbike: "/images/vehicles/dirtbike.svg",
  scooter: "/images/vehicles/scooter.svg",
};

export const vehicleImage = (m: Pick<VehicleModel, "images" | "type">) => m.images[0] ?? VEHICLE_ART[m.type];
export const tourImage = (t: Pick<Tour, "images" | "category">) => t.images[0] ?? `/images/tours/${t.category}.svg`;

/** Local SVG illustrations skip the image optimizer (it doesn't rasterize SVG). */
export const isIllustration = (src: string) => src.endsWith(".svg");

export const HERO_IMAGE = "/images/hero-sunset.svg";
