// Generates supabase/seed.sql from src/content/catalog.ts.
// Run: npm run seed:gen
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SEASONS, SEED_UNITS, TOURS, VEHICLE_MODELS } from "../src/content/catalog";
import { DEFAULT_SETTINGS } from "../src/lib/policy";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(",")}]`;
  if (typeof v === "object") return `${q(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const textArr = (a: string[]) => (a.length ? `${q(a)}::text[]` : `'{}'::text[]`);

const out: string[] = ["-- GENERATED by scripts/gen-seed.ts — do not edit by hand.", ""];

for (const m of VEHICLE_MODELS) {
  out.push(
    `insert into vehicle_models (id, slug, type, brand, name, engine_cc, seats, transmission, min_age, price_8h_cents, price_day_cents, price_week_cents, deposit_cents, images, content, sort) values (` +
      [m.id, m.slug, m.type, m.brand, m.name, m.engineCc, m.seats, m.transmission, m.minAge, m.price8hCents, m.priceDayCents, m.priceWeekCents, m.depositCents]
        .map(q)
        .join(", ") +
      `, ${textArr(m.images)}, ${q(m.content)}, ${m.sort}) on conflict (id) do nothing;`,
  );
  const n = SEED_UNITS[m.slug] ?? 1;
  for (let i = 1; i <= n; i++) {
    out.push(`insert into vehicles (model_id, label) values (${q(m.id)}, ${q(`${m.name} #${i}`)});`);
  }
}
out.push("");

for (const t of TOURS) {
  out.push(
    `insert into tours (id, slug, category, duration_hours, overnight, start_time, days_of_week, price_cents, min_pax, max_pax, difficulty, images, content, sort) values (` +
      [t.id, t.slug, t.category, t.durationHours, t.overnight, t.startTime].map(q).join(", ") +
      `, '{${t.daysOfWeek.join(",")}}'::int[], ${[t.priceCents, t.minPax, t.maxPax, t.difficulty].join(", ")}, ${textArr(t.images)}, ${q(t.content)}, ${t.sort}) on conflict (id) do nothing;`,
  );
}
out.push("");

for (const s of SEASONS) {
  out.push(`insert into seasons (name, start_date, end_date, multiplier) values (${[s.name, s.startDate, s.endDate, s.multiplier].map(q).join(", ")});`);
}
out.push("", `insert into settings (key, value) values ('business', ${q(DEFAULT_SETTINGS)}) on conflict (key) do nothing;`, "");

writeFileSync(join(__dirname, "..", "supabase", "seed.sql"), out.join("\n"));
console.log(`seed.sql written: ${VEHICLE_MODELS.length} models, ${TOURS.length} tours`);
